### ISSUE TITLE
colorizeAbout replaces About

### ISSUE THREAD

**Issue by srobb1** [elsiklab/multibigwig#10]
Hi,

When I add   `"colorizeAbout" : "true"` , to my conf file it replaces the metadata in the about track box. I thought the colors would be added to the metadata.

Thanks,
Sofia

**Comment by cmdcolin** [comment]
Yea that is true. It was actually my first attempt at "subclassing" the about box with this feature but I imagine it could do what you mention as well with a little adjustment

**Comment by cmdcolin** [comment]
Should be fixed now!
