### ISSUE TITLE
Legend for MultiXYPlot

### ISSUE THREAD

**Issue by mgalland** [elsiklab/multibigwig#11]
Thanks for this very nice plugin. I am a big fan of the MultiDensity plugin.
I'd like to know whether it would be possible to display a legend for the MultiXYPlot class. For now, we can see multiple XY curves but we don't know to which sample they each belong.
That would be an awesome improvement.
Best
Marc

**Comment by cmdcolin** [comment]
The only thing that exists currently is called "colorizeAbout" which adds a small "legend" to the "About this track" dialog box.

I think this could still be improved though. The legend could even be rendered in the top right or it could dynamically display scores for each one during mouseover https://github.com/elsiklab/multibigwig/issues/2 which would probably be ideal

**Comment by cmdcolin** [comment]
Glad that you like the plugin!

**Comment by cmdcolin** [comment]
Screenshot when enabling "colorizeAbout": true

![screenshot-localhost-2017-04-12-10-05-03](https://cloud.githubusercontent.com/assets/6511937/24961674/9bcc5316-1f67-11e7-9315-defe0af9df39.png)

**Comment by keiranmraine** [comment]
@cmdcolin , is colorizeAbout available for all tracks or just this?

**Comment by cmdcolin** [comment]
colorizeAbout is a special option for tracks in multibigwig. I know that perhaps the idea of a legend should be available from other jbrowse tracks too though :)

**Comment by cmdcolin** [comment]
@keiranmraine this is the code that customizes the "About this track" dialog for this plugin

https://github.com/elsiklab/multibigwig/blob/master/js/View/Track/MultiWiggleBase.js#L82-L93
