### ISSUE TITLE
Problems with phantom.js

### ISSUE THREAD

**Issue by LuisSoares** [elsiklab/multibigwig#12]
The multibigwig tracks won't render with phantom.js rasterize.

**Comment by cmdcolin** [comment]
Looks like there may have been an issue where multibigwig was using es6 javascript feature which phantomjs didn't support

That should be fixed on master now!

If you want you probably want to also increase the default timeout in rasterize.js, the default timeout is often too low

Here is phantomjs rendered screenshot :)

![jbrowse](https://cloud.githubusercontent.com/assets/6511937/25764119/60ae1382-31b4-11e7-9ab0-e76c34c928a4.png)

**Comment by cmdcolin** [comment]
Let me know if that helps

**Comment by cmdcolin** [comment]
Maybe close for now :)

**Comment by LuisSoares** [comment]
It works with the latests master repository. Thanks a lot for your help Colin, sorry for the delay.

**Comment by cmdcolin** [comment]
No worries. appreciate the notification of the issue !
