### ISSUE TITLE
How to Configure MultiBigWig file set for different zoom level ?

### ISSUE THREAD

**Issue by arpanda** [elsiklab/multibigwig#23]
I have few **different sets of data with various bin sizes**. I would like to show these data sets depending on the present viewed length of the genome. 

Consider a situation where a representative read depth values were calculated for different bin sizes (100, 1000, 10000, etc). For each bin, there are some bigwig file( or bigwig track). Now, if the user views a segment (i.e.; 1 MB, 10MB, 50 MB) of the genome through JBrowse, we would like to show small bin size data for small segments and big bin size data for big segments.

**Comment by cmdcolin** [comment]
I created this plugin https://github.com/cmdcolin/multiscalebigwig and it is "compatible" with multibigwig, so each urlTemplate in the urlTemplates list can specify that it uses the multiscalebigwig storeClass

**Comment by cmdcolin** [comment]
should be fixed by use of the plugin :)
