### ISSUE TITLE
Can not load resource MultiBigWig/Store/SeqFeature/MultiBigWig

### ISSUE THREAD

**Issue by Jacob-D-Christiansen** [elsiklab/multibigwig#26]
Hello, I am trying to install your plugin. I can get it to have the option on the side bar for a multi big wig track but if I click it it crashes and leaves an error that says "can not load resource MultiBigWig/Store/SeqFeature/MultiBigWig"

**Comment by cmdcolin** [comment]
To install plugins with JBrowse post 1.13.0 you have to re-run setup.sh after putting the plugin in the plugins folder

This is just due to a change in how jbrowse works, it requires a webpack rebuild. See the important note here http://gmod.org/wiki/JBrowse_FAQ#How_do_I_install_a_plugin

**Comment by cmdcolin** [comment]
You will also need the "dev" version, or alternatively a full github clone of jbrowse, to work with plugins

**Comment by cmdcolin** [comment]
Maybe I'll close for now? Feel free to let me know if you have more questions though
