### ISSUE TITLE
Singular track recieved through REST api call

### ISSUE THREAD

**Issue by Jacob-D-Christiansen** [elsiklab/multibigwig#29]
Hello, 
I am building an app where a single track needs to be gotten through a REST api call. How would you recommend going about doing this to best work with multiBigWig? If need be all of the tracks could be called through the api

**Comment by Jacob-D-Christiansen** [comment]
Currently what happens is that it sends an error back in the console saying:
'''
TypeError: store._deferred is undefined      11.bundle.js line 625 > eval:25:17
'''
This is the current set up in conf file
'''
[tracks.interactive]
key=Interactive MultiXYPlot
type=InteractivePeakAnnotator/View/Track/MultiXYPlot
urlTemplates+=json:{"url":"volvox_microarray.bw", "name": "volvox_positive", "color": "#235"}
urlTemplates+=json:{"storeClass": "JBrowse/Store/SeqFeature/REST", "baseUrl":"http://127.0.0.1:5000", "name": "volvox_positive", "color": "#235"}
storeClass=MultiBigWig/Store/SeqFeature/MultiBigWig
storeConf=json:{"storeClass": "InteractivePeakAnnotator/Store/SeqFeature/Features"}
max_score=150
'''

**Comment by Jacob-D-Christiansen** [comment]
the error leads to an error on line 44 of "MultiBigWig.js"
"return store._deferred.features;"

**Comment by cmdcolin** [comment]
@Jacob-D-Christiansen can you try to checkout this branch of this repo and try it out? https://github.com/elsiklab/multibigwig/pull/30

It proposes a fix...it should be a bit cleaner in the code altogether too because the bug you were running into seems like code that can just be deleted

**Comment by cmdcolin** [comment]
Should be fixed in 0.9.2
