### ISSUE TITLE
Sort problem with numeric label

### ISSUE THREAD

**Issue by wezen** [elsiklab/multibigwig#9]
Hello,

Multibigwig with numeric labels are sorted but urls are not.

**First test**, files and labels are sorted in config file. Track display is correct.

Part of configuration file:
> urlTemplates+=json:{"url":"tracks/test123.bw","name": "123", "color": "#FFF"}
> urlTemplates+=json:{"url":"tracks/test234.bw","name": "234", "color": "#FFF"}
> urlTemplates+=json:{"url":"tracks/test345.bw","name": "345", "color": "#FFF"}`

**Second test**, test123.bw is placed in last position. Track display is wrong.
Labels are sorted and files are not sorted.

Part of configuration file:
> urlTemplates+=json:{"url":"tracks/test234.bw","name": "234", "color": "#FFF"}
> urlTemplates+=json:{"url":"tracks/test345.bw","name": "345", "color": "#FFF"}
> urlTemplates+=json:{"url":"tracks/test123.bw","name": "123", "color": "#FFF"}

Screenshot.
![jbrowse_multibigwig](https://cloud.githubusercontent.com/assets/1208399/21353777/cd47d5d0-c6c7-11e6-8725-572a8f7c1a40.png)

thanks

**Comment by cmdcolin** [comment]
Thanks for the report. I guess maybe there is no sorting at all? Looks like it just uses the order that is specified in the urlTemplates config. Would you prefer a sorting option?

**Comment by cmdcolin** [comment]
Oh there is a difference between the "file display" and label...That may be a bug

**Comment by cmdcolin** [comment]
@wezen not sure if I can reproduce this. Have you tried clearing your cache and refreshing page? The .conf files get cached pretty aggressively

**Comment by cmdcolin** [comment]
Can't reproduce bug. If it is still a problem please let me know!!!


otherwise I think close for now
